#!/usr/bin/env sh

if test "$1"
then
    conf_path=$1
    shift;
else
    conf_path="."
fi

export PG_SRC_PATH=$(cd $conf_path; pwd)

if [ "$1" != "" ]
then

    if [ "$1" = "minimal" ]
    then
        shift;
        $conf_path/configure --prefix=$PGHOME --enable-debug --enable-cassert --enable-depend --enable-tap-tests BISONFLAGS="-v" $@

    elif [ "$1" = "coverage" ]
    then
        shift;
        $conf_path/configure --prefix=$PGHOME --enable-debug --enable-cassert --enable-depend --enable-tap-tests --enable-coverage BISONFLAGS="-v" $@

    elif [ "$1" = "extra" ]
    then
        shift;
        $conf_path/configure --prefix=$PGHOME --with-perl --with-python --enable-nls --enable-debug --enable-cassert --enable-depend --enable-tap-tests BISONFLAGS="-v" $@

    elif [ "$1" = "buildfarm" ] # Tested on Ubuntu 18.04 LTS
    then
        shift;
        $conf_path/configure --enable-debug --enable-cassert --enable-nls --with-perl \
            --with-python --with-tcl --with-gssapi --with-openssl --with-libxml \
            --with-libxslt --with-ldap --with-icu --with-zstd \
            --with-rsocket --enable-tap-tests --with-tclconfig=/usr/lib/tcl8.6 \
            --prefix=$PGHOME $@
    else
        $conf_path/configure --prefix=$PGHOME --enable-debug --enable-cassert --enable-depend --enable-tap-tests BISONFLAGS="-v" $@
    fi

else
    $conf_path/configure --prefix=$PGHOME --enable-debug --enable-cassert --enable-depend --enable-tap-tests BISONFLAGS="-v"
fi
