#! /usr/bin/env sh

if test "$1";
then
    conf_path=$1
else
    conf_path="."
fi

$conf_path/configure --prefix=$PGHOME --enable-debug --enable-cassert --enable-depend --enable-tap-tests BISONFLAGS="-v"
