#!/usr/bin/env sh

if test "$1" && test "$1" = "set"
then
    if test "$2"
    then
        PG_WORKSPACE_PATH=$(cd $2; pwd)
    else
        PG_WORKSPACE_PATH=$(pwd)
    fi

    export PG_WORKSPACE_PATH=$PG_WORKSPACE_PATH
    export PGHOME=$PG_WORKSPACE_PATH/postgres_bin
    export PG_CONFIG=$PGHOME/bin/pg_config
    export PATH=$PGHOME/bin:$PATH
    export PGDATA=$PG_WORKSPACE_PATH/postgres_data
    export CFLAGS="-O0 -g"
    # export CFLAGS="-Og -g"

    if [ -d "$HOME/perl5" ]; then
        export PATH="$HOME/perl5/bin${PATH:+:${PATH}}";
        export PERLTIDY="$HOME/perl5/bin/perltidy";
        export PERLCRITIC="$HOME/perl5/bin/perlcritic";
        export PERL5LIB="$HOME/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}";
        export PERL_LOCAL_LIB_ROOT="$HOME/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}";
        export PERL_MB_OPT="--install_base \"$HOME/perl5\"";
        export PERL_MM_OPT="INSTALL_BASE=$HOME/perl5";
    fi

    # Restricted by macOS
    # export LD_LIBRARY_PATH="$PG_WORKSPACE_PATH/postgres_bin/lib"
else
    env | grep PG | sort
    env | grep PERL | sort
fi
