#!/usr/bin/env sh

if test "$(uname -s)" != "Darwin"
then
    mkcmd=make
else
    mkcmd=gmake
fi

if [ "$1" != "" ]
then
    $mkcmd $@ && echo '\n================\nYOU ARE ALL GOOD\n================' || echo '\n==============\nYOU ARE FUCKED\n=============='
else
    $mkcmd -j$(getconf _NPROCESSORS_ONLN) -Otarget check-world && echo '\n================\nYOU ARE ALL GOOD\n================' || echo '\n==============\nYOU ARE FUCKED\n=============='
fi
